version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/usr/src/app
      - gem-store:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql-data:
  gem-store:
