FROM nginx:1.13.1
MAINTAINER mmts1007

# FIXME: assets をここに配置する方法を決める
# 同一プロジェクトならシンボリックリンクで良いが、別プロジェクトにした場合は URL で指定する??
COPY assets /usr/share/nginx/assets
COPY default.conf.template /tmp

CMD ["/bin/bash", "-c", "envsubst '$$NGINX_PORT $$SERVER_NAME $$PROXY_PASS' < /tmp/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
